name: Yamllint-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ixxel/unit-tests-alpine:latest
    steps:
    - name: Git clone repo
      uses: actions/checkout@v2
    - name: Yamllint scan
      uses: ixxeL-actions/yamllint@main
      with:
        format: 'colored'
        strict: 'false'
        no-warnings: 'false'
        exit-zero: 'true'
        working-dir: '.'